In [5]:
import numpy as np

In [4]:
a = np.arange(12).reshape(-1,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#Ambiguity
# b = np.arange(12).reshape(-1,-1)--> Do not able to reshape 

### Sorting

In [11]:
a = np.array([7,0,4,8,2,1,3,5,6,9])

In [12]:
a

array([7, 0, 4, 8, 2, 1, 3, 5, 6, 9])

In [13]:
a_sorted = np.sort(a) #--> Return a copy of the array, leaving the original array unchanged.
a_sorted

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a

array([7, 0, 4, 8, 2, 1, 3, 5, 6, 9])

In [15]:
a.sort() #inplace sorting and changes the original array

In [16]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Element Wise operations(Not In-place)

In [18]:
a = np.arange(1,6)

In [19]:
a

array([1, 2, 3, 4, 5])

In [20]:
a*5

array([ 5, 10, 15, 20, 25])

In [21]:
a

array([1, 2, 3, 4, 5])

In [22]:
b = np.arange(6,11)

In [23]:
b

array([ 6,  7,  8,  9, 10])

In [24]:
a*b
#[1,2,3,4,5] * [6,7,8,9,10] = [6,14,24,36,50]
#! Both must have same shape

array([ 6, 14, 24, 36, 50])

In [25]:
c = np.array([1,2,3])

In [26]:
c

array([1, 2, 3])

In [27]:
a*c
#! Didnot work because of shape mismatch

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

#### Trying on 2-D array

In [28]:
d = np.arange(12).reshape(3,4)

In [29]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
e = np.arange(13,25).reshape(3,4)

In [31]:
e

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [32]:
d*e

array([[  0,  14,  30,  48],
       [ 68,  90, 114, 140],
       [168, 198, 230, 264]])

In [33]:
d*5

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [34]:
'''
Array * number--> Works
Array * Array(Same Shape) --> Works if both have same shape
Array * Array (Different shape)--> Does not work if both have different shape
'''

'\nArray * number--> Works\nArray * Array(Same Shape) --> Works if both have same shape\nArray * Array (Different shape)--> Does not work if both have different shape\n'

## Matrix Multiplication

In [35]:
# No of columns in array 1 should be equal to no of rows in array 2

In [36]:
#(A,B) * (B,C) = (A,C)
# (2,2) * (2,3) = (2,3)

In [37]:
a = np.arange(1,13).reshape(3,4)
b = np.arange(2,14).reshape(4,3)

In [38]:
a.shape

(3, 4)

In [39]:
b.shape

(4, 3)

In [40]:
#* 1st Way
np.dot(a,b)
# b can be a scaler value like a number 1 ,2 ,3 ,etc

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [41]:
#* 2nd Way
np.matmul(a,b)

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [42]:
#* 3rd Way
a@b

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

# Vectorization/Vectorize

In [1]:
'''
Array -> Function -> Modified Array -> Loops
'''

'\nArray -> Function -> Modified Array -> Loops\n'

In [6]:
a = np.arange(10)

In [7]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
def random_opertation(x):
    if x %2 ==0:
        x+=2
    else:
        x-=2
    return x

In [9]:
random_opertation(a)
#! Error because it is expecting a scaler value

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [10]:
a % 2
# This will work because numpy support element wise operation

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [11]:
cool_operation = np.vectorize(random_opertation)

In [13]:
type(cool_operation)

numpy.vectorize

In [12]:
cool_operation(a)

array([ 2, -1,  4,  1,  6,  3,  8,  5, 10,  7])

In [14]:
import math

In [15]:
math.log(5)

1.6094379124341003

In [20]:
math.log(a)

TypeError: only length-1 arrays can be converted to Python scalars

In [18]:
using_vectorWithMathLog = np.vectorize(math.log)

In [21]:
# using_vectorWithMathLog(a)

# Broadcasting

In [25]:
a = np.tile([0,10,20,30],(3,1))

In [26]:
a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [27]:
a = a.T

In [28]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [29]:
b = np.tile([0,1,2], (4,1))

In [30]:
b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [31]:
# 1st Case
a+b
# Since a and b have the same shape. so, they can be added without any problem

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [32]:
c = np.array([0,1,2])

In [33]:
c

array([0, 1, 2])

In [34]:
# Case-2
a + c
# c was broadcasted  vertically to the shape of a

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [35]:
d = np.array([0,10,20,30])

In [42]:
# ALso can rehsape the array
# d = d.reshape(-1,1) or (4,1)
d = d[:,None]

In [43]:
d

array([[[ 0]],

       [[10]],

       [[20]],

       [[30]]])

In [44]:
# Case-3
d + c
# d was stacked (broadcasted) horizontally to the shape of c
# c was stacked (broadcasted) vertically to the shape of d

array([[[ 0,  1,  2]],

       [[10, 11, 12]],

       [[20, 21, 22]],

       [[30, 31, 32]]])

In [45]:
# Case-4
x = np.arange(8).reshape(2,4)
y = np.arange(16).reshape(4,4)

In [46]:
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [47]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
x + y

ValueError: operands could not be broadcast together with shapes (2,4) (4,4) 

In [50]:
'''
2D Array(+,-,*,/)
A+A (same Shape)--> Works
A+A(1D) --> Works
A+number--> Works
A+A (Different Shape)--> Does not work
'''

'\n2D Array(+,-,*,/)\nA+A (same Shape)--> Works\nA+A(1D) --> Works\nA+number--> Works\nA+A (Different Shape)--> Does not work\n'