In [1]:
import numpy as np

# Question 1


In [2]:
arr = 2*np.arange(0,2,0.5)

In [3]:
arr

array([0., 1., 2., 3.])

In [4]:
if arr <=0.6:
  print("satisfy")
else:
  print("not satisfy")

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

# Question 2

In [5]:
v = np.array([200,300,400])

In [6]:
v

array([200, 300, 400])

In [7]:
v[:,None]

array([[200],
       [300],
       [400]])

In [8]:
x = np.array([[200,200,200], [300,300,300], [400,400,400]])

In [9]:
x

array([[200, 200, 200],
       [300, 300, 300],
       [400, 400, 400]])

In [10]:
x/v[:,None]

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
(x/v[:,None])[1][1]

1.0

## B part


In [14]:
p = np.array([[0],[10],[20]])
q = np.array([10,11,12])

In [15]:
p

array([[ 0],
       [10],
       [20]])

In [16]:
q

array([10, 11, 12])

In [17]:
p+q

array([[10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

# Question 3

In [18]:
a = np.array([[16,5],[81,6],[33,1]])
a

array([[16,  5],
       [81,  6],
       [33,  1]])

In [19]:
x = np.transpose(a)

In [20]:
x

array([[16, 81, 33],
       [ 5,  6,  1]])

In [21]:
x.reshape(2,3)
x

array([[16, 81, 33],
       [ 5,  6,  1]])

In [22]:
x.flatten()

array([16, 81, 33,  5,  6,  1])

# Question 5


In [23]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
a[-2,-2]

5

In [26]:
a.T[-2,-2]

5

In [2]:
a = np.arange(0,20).reshape(5,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [18]:
row_array = a[-2:-5:-1]
row_array

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7]])

In [29]:
col_array = row_array[:,-3:]
col_array

array([[13, 14, 15],
       [ 9, 10, 11],
       [ 5,  6,  7]])