# 2-D Arrays


In [7]:
import numpy as np

In [3]:
a = np.array(range(16))

In [4]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
a.shape

(16,)

In [6]:
a.ndim

1

### Reshape


In [7]:
a.reshape(4,4)
# Elements = 16
# Spaces = 4*4 = 16
# spaces = elements --> so reshape will happen

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [8]:
#! Error
a.reshape(4,5)
# Elements = 16
# Spaces = 4*5 = 20
# spaces > elements --> so reshape will not happen

<class 'ValueError'>: cannot reshape array of size 16 into shape (4,5)

In [9]:
a.reshape(8,-1)
#-1 Denotes that the you want python to automatocally decide the number of columns

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [10]:
a.reshape(-1,4)
#-1 Denotes that the you want python to automatocally decide the number of rows

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
# a.reshape(-1,-1) --> wrong Amguity

ValueError: can only specify one unknown dimension

In [13]:
a = a.reshape(8,2)

In [14]:
len(a) #No of rows

8

In [15]:
len(a[0]) #No of Cols

2

In [16]:
# FUNCTION CHAINING
Step-2
a = np.arange(12)

In [17]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
# Step-2
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
#Step1 +  Step 2
b = np.arange(12).reshape(3,4)

In [21]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
b.shape

(3, 4)

In [23]:
b.T # T represents the transpose of any matrix in numpy

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [24]:
b.T.shape

(4, 3)

In [25]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
b[0][1]

1

In [27]:
b[0,1] # This only worls woth numpy arrays --. NOT WITH PYTHON LIST

1

In [29]:
c = np.arange(9).reshape(3,3)

In [30]:
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
c[[0,1,2],[0,1,2]] #(c[0,0] , c[1,1]  ,  c[2,2])

array([0, 4, 8])

In [33]:
test = np.arange(64).reshape(8,8)

In [34]:
test

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [35]:
test[list(range(8)), list(range(8))]

array([ 0,  9, 18, 27, 36, 45, 54, 63])

In [36]:
test[list(range(len(test))), list(range(len(test)))]

array([ 0,  9, 18, 27, 36, 45, 54, 63])

In [37]:
#BY default slicing is done on rows

In [38]:
a = np.arange(12).reshape(3,4)

In [39]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
a[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [41]:
a[:2,:2]

array([[0, 1],
       [4, 5]])

In [42]:
a[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [46]:
a[1::2, 1:4:2]

array([[5, 7]])

In [47]:
# Quiz
a = np.array([1,2,3,4,5])
b = np.array([8,7,6])


a[3:] = b[::-2]

In [48]:
a


array([1, 2, 3, 6, 8])

In [49]:
a = np.arange(12).reshape(4,3)

In [50]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [51]:
a<6

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False],
       [False, False, False]])

In [52]:
a[a<6]

array([0, 1, 2, 3, 4, 5])

# Aggreate Functions

In [53]:
a = np.arange(1,11)

In [54]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
np.sum(a)

55

In [56]:
np.mean(a)

5.5

In [57]:
np.min(a)


1

In [58]:
np.max(a)


10

In [59]:
a = np.arange(12).reshape(3,4)

In [60]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
np.sum(a)

66

In [63]:
np.sum(a, axis=0)


array([12, 15, 18, 21])

# Logical Functions

## ANY VS ALL

In [64]:
prices = np.array([50,45,25,20,35])

In [65]:
prices

array([50, 45, 25, 20, 35])

In [66]:
# I can Purchase item upto 30 rs

In [67]:
can_affort = np.any(prices <=30)
#Return True if the condition is true fro even a single value

In [68]:
can_affort

True

In [70]:
task_completion = np.array([1,1,1,1,1,1,0])

In [73]:
can_go_out_play = np.all(task_completion == 1)
# returns True if all the values satisfy the condition

In [74]:
can_go_out_play

False

In [78]:
a = np.array([3,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])

In [79]:
((a<=b) &(b<=c)).all()

False

In [80]:
a = np.array([-3,4,27,34,-2,0,-45,-11,4,0])

In [81]:
a

array([ -3,   4,  27,  34,  -2,   0, -45, -11,   4,   0])

In [84]:
a[a>0] = 1
a[a<0] = -1

#Setting values for elements selected via fancy indexing

In [85]:
a

array([-1,  1,  1,  1, -1,  0, -1, -1,  1,  0])

In [86]:
# np.where(condition, value_if_true, value_if_false)

In [87]:
prices = np.array([45,55,60,30,75,20,100,90])

In [88]:
prices

array([ 45,  55,  60,  30,  75,  20, 100,  90])

In [89]:
discounted_prices = np.where(prices>50, prices*0.9, prices)

In [90]:
discounted_prices

array([45. , 49.5, 54. , 30. , 67.5, 20. , 90. , 81. ])