In [1]:
import numpy as np

In [3]:
x = np.zeros(3)
x

array([0., 0., 0.])

# Question 1

In [4]:
a = np.ones((5,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Question 2

In [7]:
arr = np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])
arr

array([[ 2,  3,  4,  5],
       [ 1,  7,  3,  5],
       [ 2,  8,  6,  9],
       [11, 23, 12, 19]])

In [11]:
def func(x,y):
  return x*y
vec = np.vectorize(func)

### Option-A

In [12]:
arrA = np.array([[2,2,2,2]])

In [13]:
vec(arr,arrA)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

### Option B

In [15]:
arrB = np.array([[2],[2],[2],[2]])

In [16]:
vec(arr,arrB)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

### Option C

In [17]:
arrC = 2
vec(arr,arrC)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

# Question 3

In [ ]:
def specific_elements(mat1,mat2,r1,r2,c1,c2):
    '''mat1,mat2 are the two 2d numpy array.
       r1,r2 are the start and end of rows indices
       c1,c2 are the start and end of columns indices
       Output = Return a numpy array according to indices'''
   # STEP1 CHECK whether matrix multiplication is possible
    m1=mat1.shape[1]
    n2=mat2.shape[0] 
    if(m1!=n2): 
        return -1

# STEP 2 Perform matrix multiplication
    matmul_array = np.dot(mat1,mat2)
 
    # STEP 3 slice the array based on range value
    result = matmul_array[r1:r2,c1:c2]
 
    return result


# Question 4

In [ ]:
def sort_birds(birds, age):
    '''
    INPUT: birds, age -> 1D numpy array

    OUTPUT: result -> sorted bird 1D array
    '''

# STEP 1 : Get the sorted index of age.
    sorted_age_index = np.argsort(age)


# STEP 2: Use the index from previous step to get sorted birds
    result = birds[sorted_age_index] 

    return result

# Question 5

### Option A

In [18]:
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

['Astha' 'Raghavendra' 'Ram']


### Option B

In [19]:
arr1 = np.array(['Ram','Astha','Brahat'])
arr2 = np.array(['Shyam','Kalyan','Naveen'])
arr1 > arr2

array([False, False, False])