In [1]:
import numpy as np

In [2]:
a = np.arange(16).reshape(4,4)

In [3]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
np.split(a,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [12]:
x = np.array([[[0,1,2],[3,4,5],[6,7,8]],[[9,10,11],[12,13,14],[15,16,17]]])

In [13]:
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [14]:
x[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [17]:
b = np.arange(1,10).reshape(3,3)

In [18]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.hstack((b,b[:,[0]]))

array([[1, 2, 3, 1],
       [4, 5, 6, 4],
       [7, 8, 9, 7]])

In [23]:
b[:,[0]]

array([[1],
       [4],
       [7]])

In [24]:
b[:,0]

array([1, 4, 7])