In [4]:
import numpy as np

In [5]:
a = [1,2, "This is a massive String which will take  alot of Data"]

In [6]:
a #Heterogeneous

[1, 2, 'This is a massive String which will take  alot of Data']

In [7]:
# Numpy ONLY HANDLES HOMOGENOUS DATA!!!

In [9]:
import numpy as np

In [2]:
a =[1,2,3,4,5]

In [3]:
a

[1, 2, 3, 4, 5]

In [18]:
b = np.array(a)

In [19]:
b

array([1, 2, 3, 4, 5])

In [20]:
res = [i**2 for i in a]

In [21]:
res

[1, 4, 9, 16, 25]

# Numpy Array support Element wise operations

In [24]:
b**2


array([ 1,  4,  9, 16, 25])

In [26]:
## Time

In [5]:
%timeit [i**3 for i in range(1000000)]

77.3 ms ± 2.92 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
l = np.array(range(10000))

In [8]:
%timeit l**3

13 µs ± 243 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


#### Why Numpy is Faster?
- Homogenous
- Divide task in parallel processes
- Numpy functions are implemented in C


In [33]:
a = np.array(range(10000))

In [34]:
a.ndim # Tells how many dimensions there are in the array

1

In [35]:
a.shape #Tells about row col,etc

(10000,)

In [37]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [38]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
b.ndim

2

In [40]:
b.shape

(3, 3)

In [42]:
a= np.array([1,2,3,4,5,6,7,8])

In [44]:
a.ndim

1

In [47]:
a.shape

(8,)

In [48]:
## np.arange

In [49]:
a1 = np.arange(1,5)

In [50]:
a1

array([1, 2, 3, 4])

In [51]:
a2 = np.arange(1,5,2)

In [52]:
a2

array([1, 3])

In [53]:
#np.arange can also work with float numbers

In [54]:
a3 = np.arange(1,5,0.5)

In [55]:
a3


array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [56]:
1.

1.0

In [57]:
a3

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [58]:
a3[0]

1.0

In [59]:
a3[-1]

4.5

In [60]:
a3[2:5]

array([2. , 2.5, 3. ])

In [61]:
a=[1,2,3,4,5.6]

In [62]:
a = np.array(a)

In [63]:
a

array([1. , 2. , 3. , 4. , 5.6])

In [64]:
b = np.array(["Kuldeep Saini",1,2,3,4])

In [65]:
b

array(['Kuldeep Saini', '1', '2', '3', '4'], dtype='<U13')

In [66]:
c = np.array([1,2,3,4.0])

In [67]:
c

array([1., 2., 3., 4.])

In [68]:
#Intrinsticc Typecasting --> Happens automatically
#Extrinstic Typecasting --> Manually based on user preference

In [70]:
d = np.array([1,2,3,4,5], dtype="float")

In [71]:
d

array([1., 2., 3., 4., 5.])

In [72]:
e = np.array(["this","is", "wrong cannot happen"], dtype="float")

ValueError: could not convert string to float: 'this'

In [83]:
m1 = np.array(range(1,11))

In [74]:
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
m1>6

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [76]:
m1[2] = 9

In [77]:
m1

array([ 1,  2,  9,  4,  5,  6,  7,  8,  9, 10])

In [78]:
a = [1,2,3,4,5]

In [79]:
a[1,2,4]#Fetching elemnts at multiple index at the same is not possible in python

TypeError: list indices must be integers or slices, not tuple

In [80]:
# IT is possible in numpy array

In [85]:
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
m1[m1%2==0]

array([ 2,  4,  6,  8, 10])

In [86]:
'''
Break Down -->
--> [1,     2,    3,   4,    5,    6,   7,    8,    9,    10]
--> [False,True,False,True,False,True,False,True, false, True]
'''

'\nBreak Down -->\n--> [1,     2,    3,   4,    5,    6,   7,    8,    9,    10]\n--> [False,True,False,True,False,True,False,True, false, True]\n'

# NPS CASE 

In [91]:
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: C:\Users\kulde\survey.txt

  0%|          | 0.00/2.55k [00:00<?, ?B/s]
100%|##########| 2.55k/2.55k [00:00<?, ?B/s]


In [93]:
score = np.loadtxt("survey.txt", dtype="int")

In [94]:
type(score)

numpy.ndarray

In [95]:
score

array([ 7, 10,  5, ...,  5,  9, 10])

In [96]:
score.shape

(1167,)