In [1]:
import numpy as np

In [2]:
a = np.arange(4)

In [3]:
a

array([0, 1, 2, 3])

In [5]:
b = a.reshape((2,2))
b

array([[0, 1],
       [2, 3]])

In [6]:
a[0] = 100

In [7]:
a

array([100,   1,   2,   3])

In [8]:
b

array([[100,   1],
       [  2,   3]])

In [9]:
# np.shares_memeory(array_1, array_2) returns True if both arrays share the same memory block

In [10]:
np.shares_memory(a,b) ##Shallow copy

True

In [11]:
a = np.arange(4)

In [12]:
c = a+2

In [13]:
a

array([0, 1, 2, 3])

In [14]:
c

array([2, 3, 4, 5])

In [15]:
np.shares_memory(a,c)#Deep copy

False

In [16]:
a = np.zeros(4)

In [17]:
a

array([0., 0., 0., 0.])

In [18]:
d = a*2

In [19]:
d

array([0., 0., 0., 0.])

In [20]:
#Values of a and d are same but donot share the same memory block
np.shares_memory(a,d)

False

In [21]:
a = np.arange(10)

In [22]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
b = a[::2]

In [25]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
b

array([0, 2, 4, 6, 8])

In [27]:
np.shares_memory(a,b)

True

In [28]:
a[0] = 1000

In [29]:
a

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [30]:
b

array([1000,    2,    4,    6,    8])

In [31]:
#QUiz

In [32]:
a = np.arange(6)

In [33]:
a

array([0, 1, 2, 3, 4, 5])

In [34]:
b = a[a%1==0]

In [35]:
b

array([0, 1, 2, 3, 4, 5])

In [36]:
b[0] = 10

In [37]:
a[0]

0

In [ ]:
'''
memory in Numpy-->
1. Shallow copy - Reshape, Slicing, Broadcasting
2. Deep copy - Arithmetic operations, masking, fancy indexing
'''

### How to create shallow and deep copies ?

In [39]:
a = np.arange(10)

In [40]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
# Create a shallow copy of a
a_shallow_copy = a.view()

In [42]:
np.shares_memory(a,a_shallow_copy)

True

In [43]:
a_deep_copy = a.copy()

In [44]:
np.shares_memory(a,a_deep_copy)

False

# SPLITTING DATA

In [45]:
a = np.arange(9)

In [46]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
# Splitting in n equal sections

In [48]:
np.split(a,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [49]:
# Importing Requistie
# Number of elements in the array should be divisible by the number of sections

In [50]:
b = np.arange(10)

In [51]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.split(b,5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [53]:
np.split(b,3) --> cannot split

ValueError: array split does not result in an equal division

In [54]:
b[0:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
result = np.split(b[0:-1],3)

In [56]:
result

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [57]:
# Splitting in unequal sections/ on the basis of exact indices

In [58]:
c = np.arange(16)

In [59]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [60]:
np.split(c,[3,5,9])

[array([0, 1, 2]),
 array([3, 4]),
 array([5, 6, 7, 8]),
 array([ 9, 10, 11, 12, 13, 14, 15])]

### Splitting in 2-D Array

In [61]:
a = np.arange(48).reshape(8,6)

In [62]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47]])

##### hsplit

In [63]:
np.hsplit(a,3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31],
        [36, 37],
        [42, 43]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27],
        [32, 33],
        [38, 39],
        [44, 45]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29],
        [34, 35],
        [40, 41],
        [46, 47]])]

In [64]:
np.hsplit(a,[2,5])

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31],
        [36, 37],
        [42, 43]]),
 array([[ 2,  3,  4],
        [ 8,  9, 10],
        [14, 15, 16],
        [20, 21, 22],
        [26, 27, 28],
        [32, 33, 34],
        [38, 39, 40],
        [44, 45, 46]]),
 array([[ 5],
        [11],
        [17],
        [23],
        [29],
        [35],
        [41],
        [47]])]

#### vsplit

In [67]:
np.vsplit(a,4)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]),
 array([[36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]])]

In [68]:
np.vsplit(a,[1,6])

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]),
 array([[36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]])]

# Stacking
   - 

In [71]:
a = np.arange(1,5)
b = np.arange(2,6)
c = np.arange(3,7)

In [72]:
a

array([1, 2, 3, 4])

In [73]:
b

array([2, 3, 4, 5])

In [82]:
c

array([3, 4, 5, 6])

##### vstack([order of arrays])

In [75]:
# Dimension(No of cols) of all the arrays should be same
np.vstack([b,c,a])

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [1, 2, 3, 4]])

In [76]:
a = np.arange(10).reshape(2,5)

In [77]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [78]:
b = np.arange(50).reshape(10,5)

In [79]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [80]:
np.vstack([a,b])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

##### hstack([order of arrays])

In [83]:
a = np.arange(5).reshape(5,1)

In [84]:
a

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [85]:
b = np.arange(10).reshape(5,2)

In [86]:
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [88]:
np.hstack([b,a])

array([[0, 1, 0],
       [2, 3, 1],
       [4, 5, 2],
       [6, 7, 3],
       [8, 9, 4]])

In [89]:
np.hstack([b,b])

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [6, 7, 6, 7],
       [8, 9, 8, 9]])

In [90]:
np.hstack([a,a])

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

#### Concatenate--> can perform both vstack and hstack 

In [91]:
#! Issuse --> but having small issuse 
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])

In [92]:
a

array([1, 2, 3])

In [93]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
np.concatenate([a,b],axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [96]:
# Concatenate can only work if both a and b have same number of dimensions

In [116]:
# Changing dimesnion of a
a = np.array([[1,2,3]])
b = np.array([[4,5,6],[7,8,9]])


In [117]:
a.shape
a.ndim

2

In [112]:
b.shape
b.ndim

2

In [118]:
a

array([[1, 2, 3]])

In [114]:
b

array([[4, 5, 6],
       [7, 8, 9]])

In [119]:
np.concatenate([a,b],axis=0) # axis = 0 means Vstack(row wise stacking)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [122]:
np.concatenate([b,a],axis=0)

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [123]:
a = np.arange(6).reshape(3,2)
b = np.arange(9).reshape(3,3)

In [124]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [125]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [126]:
np.concatenate([a,b],axis=1) # axis = 1 means Hstack(column wise stacking)

array([[0, 1, 0, 1, 2],
       [2, 3, 3, 4, 5],
       [4, 5, 6, 7, 8]])

In [127]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6,7,8]])

In [128]:
a

array([[1, 2],
       [3, 4]])

In [129]:
b

array([[5, 6, 7, 8]])

In [131]:
#! axis = None joins and converts all the elements into a single array
np.concatenate([a,b],axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [132]:
a 

array([[1, 2],
       [3, 4]])

In [133]:
# Also convert 2-D array into 1-D array(works on only 1 array wile concatenate works on multiple arrays)
a.flatten()

array([1, 2, 3, 4])